spring:
   datasource:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/estacionamiento
      username: root
      password: haroll.mora
      #password: ENC(UiHd2//oF3r+8juwRut/uoW82iOug37Rd)
      hikari:
         poolName: pool

server:
   port: 8083
   servlet:
      context-path: /estacionamiento

